export enum POINTS_REASON {
  LESSON_COMPLETE = 'LESSON_COMPLETE',
  QUIZ_PASS = 'QUIZ_PASS',
  QUIZ_PERFECT = 'QUIZ_PERFECT',
  COURSE_COMPLETE = 'COURSE_COMPLETE',
  FIRST_ENROLLMENT = 'FIRST_ENROLLMENT',
  STREAK_BONUS = 'STREAK_BONUS',
  COMMUNITY_POST = 'COMMUNITY_POST',
  ADMIN_ADJUST = 'ADMIN_ADJUST',
}

export enum BADGE_CRITERIA {
  POINTS_THRESHOLD = 'POINTS_THRESHOLD',
  COURSES_COMPLETED = 'COURSES_COMPLETED',
  QUIZZES_PASSED = 'QUIZZES_PASSED',
  PERFECT_QUIZ = 'PERFECT_QUIZ',
  STREAK_DAYS = 'STREAK_DAYS',
  CUSTOM = 'CUSTOM',
}
