export enum GRADE_STATUS {
  PENDING = 'PENDING',
  GRADED = 'GRADED',
  RETURNED = 'RETURNED',
}

export enum ASSESSMENT_TYPE {
  QUIZ = 'QUIZ',
  ASSIGNMENT = 'ASSIGNMENT',
}

export enum SUBMISSION_STATUS {
  SUBMITTED = 'SUBMITTED',
  GRADED = 'GRADED',
  RETURNED = 'RETURNED',
  RESUBMITTED = 'RESUBMITTED',
}
